name: Notify Discord on Issues & PRs

on:
  issues:
    types: [opened, reopened, edited, closed]
  pull_request:
    types: [opened, reopened, edited, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install notifier dependencies
        working-directory: integrations/notification-bot
        run: npm ci

      - name: Send notification
        working-directory: integrations/notification-bot
        run: npm start
